version: '3.9'
services:
  mongodb:
    image: bitnami/mongodb:4.4
    volumes:
      - ./volumes/mongodb:/bitnami/mongodb
    ports:
      - "27017:27017"
  redis:
    container_name: redis1
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"
  
  